//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanePokojow
    {
        public string NazwaPokoju { get; set; }
        public string Miasto { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public int LiczbaMiejsc { get; set; }
        public int WolneMiejsca { get; set; }
        public string ŁaziekaWPokoju { get; set; }
        public Nullable<int> IDPokoju { get; set; }
    }
}
